import { useState, useEffect, useCallback } from 'react';
import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { OBJLoader } from 'three/examples/jsm/loaders/OBJLoader.js';

import { Header } from './components/Header';
import { SidebarControls } from './components/SidebarControls';
import { Viewport3D } from './components/Viewport3D';
import { Toolbar, RenderMode } from './components/Toolbar';
import { MeshStats, ModelMetrics } from './components/MeshStats';
import { ExportModal } from './components/ExportModal';
import { ColabSettingsModal } from './components/ColabSettingsModal';

import { colabApi, ColabHealthResponse } from './services/api';
import { generateOffline3DMesh } from './services/meshGenerators';
import { SAMPLE_IMAGES } from './services/sampleData';

export default function App() {
  // Model state
  const [model, setModel] = useState<THREE.Object3D | null>(null);
  const [selectedImage, setSelectedImage] = useState<string | null>(SAMPLE_IMAGES[0].dataUrl);
  const [imageName, setImageName] = useState<string>('modern_chair');

  // Viewport display controls
  const [renderMode, setRenderMode] = useState<RenderMode>('textured');
  const [showGrid, setShowGrid] = useState<boolean>(true);
  const [autoRotate, setAutoRotate] = useState<boolean>(false);
  const [resetCameraTrigger, setResetCameraTrigger] = useState<number>(0);

  // Engine & Colab settings
  const [engineMode, setEngineMode] = useState<'colab' | 'offline'>('offline');
  const [colabUrl, setColabUrl] = useState<string>(() => localStorage.getItem('colab_backend_url') || '');
  const [colabStatus, setColabStatus] = useState<'connected' | 'disconnected' | 'checking'>('disconnected');
  const [colabInfo, setColabInfo] = useState<ColabHealthResponse | null>(null);

  // Generation status
  const [isGenerating, setIsGenerating] = useState<boolean>(false);
  const [generationStep, setGenerationStep] = useState<string>('');
  const [depthScale, setDepthScale] = useState<number>(0.35);

  // Telemetry & Modals
  const [metrics, setMetrics] = useState<ModelMetrics | null>(null);
  const [isExportOpen, setIsExportOpen] = useState<boolean>(false);
  const [isSettingsOpen, setIsSettingsOpen] = useState<boolean>(false);

  // Colab Health Check
  const checkColabHealth = useCallback(async (): Promise<ColabHealthResponse | null> => {
    if (!colabUrl) {
      setColabStatus('disconnected');
      setColabInfo(null);
      return null;
    }

    setColabStatus('checking');
    try {
      colabApi.setUrl(colabUrl);
      const health = await colabApi.checkHealth();
      setColabStatus('connected');
      setColabInfo(health);
      return health;
    } catch (err) {
      setColabStatus('disconnected');
      setColabInfo(null);
      return null;
    }
  }, [colabUrl]);

  // Initial setup: check health and generate initial demo model
  useEffect(() => {
    if (colabUrl) {
      checkColabHealth();
    }
    // Generate initial offline sample so the 3D studio starts alive
    generateFromOfflineImage(SAMPLE_IMAGES[0].dataUrl);
  }, []);

  const handleSaveColabUrl = (url: string) => {
    setColabUrl(url);
    localStorage.setItem('colab_backend_url', url);
  };

  // Offline Generation Helper
  const generateFromOfflineImage = (dataUrl: string, scale = depthScale) => {
    setIsGenerating(true);
    setGenerationStep('Computing Depth Geometry...');

    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.onload = () => {
      try {
        const meshGroup = generateOffline3DMesh(img, { depthScale: scale, resolution: 120 });
        setModel(meshGroup);
      } catch (err) {
        console.error('Offline mesh generation error:', err);
        alert('Failed to generate 3D mesh: ' + err);
      } finally {
        setIsGenerating(false);
        setGenerationStep('');
      }
    };
    img.src = dataUrl;
  };

  // Colab AI 360° Generation Helper
  const generateFromColab = async (dataUrl: string) => {
    if (!colabUrl) {
      setIsSettingsOpen(true);
      return;
    }

    setIsGenerating(true);
    setGenerationStep('Sending image to Colab T4 GPU...');

    try {
      // Convert dataUrl to blob
      const res = await fetch(dataUrl);
      const blob = await res.blob();

      setGenerationStep('Neural 360° Reconstruction (~3-5s)...');
      const arrayBuffer = await colabApi.generate3DModel(blob, `${imageName}.png`);

      setGenerationStep('Loading 3D Mesh in Viewport...');
      const loader = new GLTFLoader();
      loader.parse(
        arrayBuffer,
        '',
        (gltf) => {
          setModel(gltf.scene);
          setIsGenerating(false);
          setGenerationStep('');
        },
        (err) => {
          console.error('GLTF Parse Error:', err);
          alert('Could not parse GLB generated by Colab.');
          setIsGenerating(false);
          setGenerationStep('');
        }
      );
    } catch (err: any) {
      console.error('Colab generation error:', err);
      alert(`${err.message}\n\nTip: You can switch to "Universal CPU (Offline)" in the top bar to run without Colab!`);
      setIsGenerating(false);
      setGenerationStep('');
    }
  };

  // Main Generate Handler
  const handleGenerate = () => {
    if (!selectedImage) return;

    if (engineMode === 'colab') {
      if (colabStatus !== 'connected') {
        setIsSettingsOpen(true);
        return;
      }
      generateFromColab(selectedImage);
    } else {
      generateFromOfflineImage(selectedImage, depthScale);
    }
  };

  // Handle direct 3D model file uploads (.glb / .gltf / .obj)
  const handleFileUpload3D = (file: File) => {
    const ext = file.name.split('.').pop()?.toLowerCase();
    const reader = new FileReader();

    if (ext === 'glb' || ext === 'gltf') {
      reader.onload = (e) => {
        const buffer = e.target?.result as ArrayBuffer;
        const loader = new GLTFLoader();
        loader.parse(buffer, '', (gltf) => {
          setModel(gltf.scene);
          setImageName(file.name.replace(/\.[^/.]+$/, ''));
        });
      };
      reader.readAsArrayBuffer(file);
    } else if (ext === 'obj') {
      reader.onload = (e) => {
        const text = e.target?.result as string;
        const loader = new OBJLoader();
        const obj = loader.parse(text);
        setModel(obj);
        setImageName(file.name.replace(/\.[^/.]+$/, ''));
      };
      reader.readAsText(file);
    } else {
      alert('Unsupported file type. Please upload .glb, .gltf, or .obj');
    }
  };

  const handleSelectImage = (dataUrl: string, name?: string) => {
    setSelectedImage(dataUrl);
    if (name) setImageName(name.replace(/\.[^/.]+$/, ''));
  };

  return (
    <div className="flex flex-col h-screen w-screen overflow-hidden bg-studio-900 text-slate-100">
      {/* 1. Top Navigation Bar */}
      <Header
        engineMode={engineMode}
        onToggleEngine={(mode) => setEngineMode(mode)}
        colabStatus={colabStatus}
        colabInfo={colabInfo}
        onOpenSettings={() => setIsSettingsOpen(true)}
      />

      {/* 2. Main Workspace Layout */}
      <div className="flex flex-1 h-[calc(100vh-3.5rem)] overflow-hidden">
        {/* Left Sidebar: Image upload, presets, controls */}
        <SidebarControls
          selectedImage={selectedImage}
          onSelectImage={handleSelectImage}
          onClearImage={() => setSelectedImage(null)}
          onGenerate={handleGenerate}
          isGenerating={isGenerating}
          generationStep={generationStep}
          engineMode={engineMode}
          onFileUpload3D={handleFileUpload3D}
          depthScale={depthScale}
          onDepthScaleChange={(val) => {
            setDepthScale(val);
            if (selectedImage && engineMode === 'offline') {
              generateFromOfflineImage(selectedImage, val);
            }
          }}
          onOpenExport={() => setIsExportOpen(true)}
          hasModel={!!model}
        />

        {/* Center/Right 3D Interactive Viewport */}
        <main className="flex-1 relative h-full bg-[#0d1117] flex items-center justify-center">
          {/* Floating Viewport Toolbar */}
          <Toolbar
            renderMode={renderMode}
            onSetRenderMode={setRenderMode}
            showGrid={showGrid}
            onToggleGrid={() => setShowGrid((prev) => !prev)}
            autoRotate={autoRotate}
            onToggleAutoRotate={() => setAutoRotate((prev) => !prev)}
            onResetCamera={() => setResetCameraTrigger((prev) => prev + 1)}
            onOpenExport={() => setIsExportOpen(true)}
            hasModel={!!model}
          />

          {/* Three.js 3D Canvas */}
          <Viewport3D
            model={model}
            renderMode={renderMode}
            showGrid={showGrid}
            autoRotate={autoRotate}
            resetCameraTrigger={resetCameraTrigger}
            onMetricsChange={setMetrics}
            engineMode={engineMode}
          />

          {/* Real-time Geometry Telemetry Badge */}
          <MeshStats metrics={metrics} />
        </main>
      </div>

      {/* 3. Export Modal */}
      <ExportModal
        isOpen={isExportOpen}
        onClose={() => setIsExportOpen(false)}
        model={model}
        baseFilename={imageName || 'reconstructed_model'}
      />

      {/* 4. Colab Backend Settings Modal */}
      <ColabSettingsModal
        isOpen={isSettingsOpen}
        onClose={() => setIsSettingsOpen(false)}
        colabUrl={colabUrl}
        onSaveUrl={handleSaveColabUrl}
        onRefreshHealth={checkColabHealth}
        colabInfo={colabInfo}
      />
    </div>
  );
}
